/**
 * The icon-barrel scanner behind `lib/shims/lucide-icons.ts`.
 *
 * `lucide-react-native`'s root entry re-exports all 1,747 icons under three
 * aliases each. Metro has no tree shaking on the web export, so a single
 * `import { Check } from 'lucide-react-native'` anywhere in the graph puts
 * every icon in `index-*.js` — measured at 1,836,042 B, 17.4% of the bundle.
 * The package does publish `./icons/*` subpath exports, so the fix is to
 * resolve the bare specifier to a barrel that names only the icons this repo
 * actually imports (see `metro.config.js`, web only).
 *
 * That barrel is generated, not hand-kept, and `__tests__/icon-shims.test.ts`
 * re-runs this scan and fails when it drifts — because the failure mode of a
 * missing entry is an `undefined` component at runtime, which TypeScript
 * cannot catch: `tsc` resolves `lucide-react-native` to the real package and
 * never sees the shim.
 *
 *     bun run --filter @alia/app generate:icon-shims
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
export const APP_ROOT = resolve(HERE, '..');
export const REPO_ROOT = resolve(APP_ROOT, '../..');

/** Everything whose web graph this app's export can reach. */
export const SCAN_ROOTS = [
  join(APP_ROOT, 'app'),
  join(APP_ROOT, 'components'),
  join(APP_ROOT, 'lib'),
  join(REPO_ROOT, 'packages/alia-chat/src'),
];

export const LUCIDE_BARREL = join(
  REPO_ROOT,
  'node_modules/lucide-react-native/dist/esm/lucide-react-native.mjs',
);
export const LUCIDE_SHIM = join(APP_ROOT, 'lib/shims/lucide-icons.ts');

/** Names exported by the root entry that are types, not icon components. */
const NON_ICON_EXPORTS = new Set(['LucideIcon', 'LucideProps', 'IconNode', 'createLucideIcon', 'icons']);

function walk(dir, out = []) {
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const entry of entries) {
    if (entry.name === 'node_modules' || entry.name === 'dist' || entry.name === '.git') continue;
    const path = join(dir, entry.name);
    if (entry.isDirectory()) walk(path, out);
    else if (/\.(ts|tsx)$/.test(entry.name)) out.push(path);
  }
  return out;
}

/** PascalCase export name -> kebab-case `./icons/<file>` module, read from the real barrel. */
export function readLucideIconMap() {
  const barrel = readFileSync(LUCIDE_BARREL, 'utf8');
  const map = new Map();
  for (const group of barrel.matchAll(/export \{([^}]*)\} from '\.\/icons\/([^']+)\.mjs';/g)) {
    for (const clause of group[1].split(',')) {
      const alias = clause.trim().match(/default as (\w+)/);
      if (alias) map.set(alias[1], group[2]);
    }
  }
  return map;
}

/**
 * Every name imported from a bare specifier across the scan roots, plus any
 * default/namespace import of it — which a named-export shim cannot serve, so
 * the caller has to refuse rather than silently drop it.
 */
export function scanBareImports(specifier, roots = SCAN_ROOTS) {
  const quoted = specifier.replace(/[.*+?^${}()|[\]\\/]/g, '\\$&');
  const named = new RegExp(
    `import\\s+(?:type\\s+)?\\{([^}]*)\\}\\s*from\\s*["']${quoted}["']`,
    'g',
  );
  const namespaced = new RegExp(
    `import\\s+(?!\\{|type\\s*\\{)([^;\\n]*?)\\s*from\\s*["']${quoted}["']`,
    'g',
  );
  const names = new Set();
  const namespaceImports = [];
  for (const root of roots) {
    for (const file of walk(root)) {
      const src = readFileSync(file, 'utf8');
      for (const m of src.matchAll(named)) {
        for (const clause of m[1].split(',')) {
          const name = clause.trim().replace(/^type\s+/, '').split(/\s+as\s+/)[0].trim();
          if (name) names.add(name);
        }
      }
      for (const m of src.matchAll(namespaced)) {
        namespaceImports.push(`${file}: ${m[1].trim()}`);
      }
    }
  }
  return { names: [...names].sort(), namespaceImports };
}

/**
 * The lucide scan, split into icons and everything else. Type-only imports
 * count: the shim has to satisfy them too if Metro ever sees them as values.
 */
export function scanLucideImports(roots = SCAN_ROOTS) {
  const iconMap = readLucideIconMap();
  const { names, namespaceImports } = scanBareImports('lucide-react-native', roots);
  return {
    icons: names.filter((n) => iconMap.has(n)),
    other: names.filter((n) => !iconMap.has(n)),
    namespaceImports,
    iconMap,
  };
}

export function renderLucideShim({ icons, other, iconMap }) {
  const lines = [
    '/**',
    ' * Generated by `scripts/icon-shims.mjs` — do not edit by hand.',
    ' *',
    " * `metro.config.js` resolves the bare `lucide-react-native` specifier to this",
    ' * file on WEB ONLY. The real root entry re-exports all 1,747 icons, and Metro',
    ' * does not tree shake the web export, so importing it from anywhere pulled',
    ' * 1,836,042 B of icons into `index-*.js`. This barrel names only the icons the',
    ' * repo imports, each from its own `./icons/*` subpath export.',
    ' *',
    ' * Native resolution is untouched: the redirect is gated on `platform === "web"`.',
    ' *',
    " * Adding an icon import? Re-run `bun run --filter @alia/app generate:icon-shims`.",
    ' * `__tests__/icon-shims.test.ts` fails if you forget — TypeScript will not,',
    ' * because it resolves `lucide-react-native` to the real package.',
    ' */',
    '',
  ];
  for (const name of icons) {
    lines.push(`export { default as ${name} } from 'lucide-react-native/icons/${iconMap.get(name)}';`);
  }
  if (other.length) {
    lines.push('');
    lines.push('// Type-only exports: erased at compile time, so they cost no bundle bytes.');
    lines.push(`export type { ${other.join(', ')} } from 'lucide-react-native';`);
  }
  lines.push('');
  return lines.join('\n');
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const scan = scanLucideImports();
  if (scan.namespaceImports.length) {
    console.error('Namespace/default imports of lucide-react-native cannot be shimmed:');
    for (const n of scan.namespaceImports) console.error('  ' + n);
    process.exit(1);
  }
  const unknown = scan.other.filter((n) => !NON_ICON_EXPORTS.has(n));
  if (unknown.length) {
    console.error('Unrecognised non-icon imports from lucide-react-native:', unknown.join(', '));
    process.exit(1);
  }
  writeFileSync(LUCIDE_SHIM, renderLucideShim(scan));
  console.log(`lib/shims/lucide-icons.ts: ${scan.icons.length} icons, ${scan.other.length} types`);
}
