/**
 * Markdown → Telegram HTML converter
 *
 * Converts standard Markdown (as generated by LLMs) into Telegram Bot API
 * compatible HTML using regex. Only produces tags Telegram supports:
 *   <b>, <i>, <s>, <code>, <pre>, <a href="...">
 *
 * Zero dependencies — no parser library needed.
 */

interface Placeholder {
  key: string;
  replacement: string;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

/**
 * Convert standard Markdown to Telegram-compatible HTML.
 *
 * Processing order prevents conflicts between patterns:
 *   1. Extract code blocks & inline code (protect from all processing)
 *   2. Extract links (protect URLs from entity escaping)
 *   3. Escape HTML entities in remaining text
 *   4. Convert formatting (bold+italic → bold → italic → strikethrough)
 *   5. Convert structural elements (headings, bullet lists)
 *   6. Restore placeholders
 */
export function markdownToTelegramHtml(text: string): string {
  const placeholders: Placeholder[] = [];
  let counter = 0;
  let result = text;

  function placeholder(replacement: string): string {
    const key = `\x00${counter++}\x00`;
    placeholders.push({ key, replacement });
    return key;
  }

  // 1. Extract fenced code blocks
  result = result.replace(/```(\w*)\n([\s\S]*?)```/g, (_m, lang: string, code: string) => {
    const escaped = escapeHtml(code.replace(/\n$/, ''));
    if (lang) {
      return placeholder(`<pre><code class="language-${lang}">${escaped}</code></pre>`);
    }
    return placeholder(`<pre>${escaped}</pre>`);
  });

  // 2. Extract inline code
  result = result.replace(/`([^`\n]+)`/g, (_m, code: string) => {
    return placeholder(`<code>${escapeHtml(code)}</code>`);
  });

  // 3. Extract links [text](url)
  result = result.replace(/\[([^\]]+)\]\(([^)]+)\)/g, (_m, linkText: string, url: string) => {
    return placeholder(`<a href="${url}">${escapeHtml(linkText)}</a>`);
  });

  // 4. Escape HTML entities in remaining text
  result = escapeHtml(result);

  // 5. Bold + Italic: ***text***
  result = result.replace(/\*{3}(.+?)\*{3}/g, '<b><i>$1</i></b>');

  // 6. Bold: **text**
  result = result.replace(/\*{2}(.+?)\*{2}/g, '<b>$1</b>');

  // 7. Italic: *text* (not at line start followed by space — that's a bullet)
  result = result.replace(/(?<=\s|^)\*(?!\s)(.+?)(?<!\s)\*(?!\*)/gm, '<i>$1</i>');

  // 8. Strikethrough: ~~text~~
  result = result.replace(/~~(.+?)~~/g, '<s>$1</s>');

  // 9. Headings: # text → bold (Telegram has no heading tags)
  result = result.replace(/^#{1,6}\s+(.+)$/gm, '<b>$1</b>');

  // 10. Bullet lists: lines starting with - or * followed by space → •
  result = result.replace(/^(\s*)[-*]\s+/gm, '$1\u2022 ');

  // 11. Restore placeholders
  for (let i = placeholders.length - 1; i >= 0; i--) {
    result = result.replace(placeholders[i].key, placeholders[i].replacement);
  }

  return result.trim();
}

/**
 * Strip Markdown syntax for plain-text fallback.
 * Used when Telegram rejects the HTML — produces clean readable text
 * instead of showing raw asterisks and brackets.
 */
export function stripMarkdown(text: string): string {
  return text
    // Code blocks: keep content, remove fences
    .replace(/```\w*\n([\s\S]*?)```/g, '$1')
    // Inline code: keep content
    .replace(/`([^`\n]+)`/g, '$1')
    // Links: show text (url)
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '$1 ($2)')
    // Bold+italic
    .replace(/\*{3}(.+?)\*{3}/g, '$1')
    // Bold
    .replace(/\*{2}(.+?)\*{2}/g, '$1')
    // Italic (not bullet lists)
    .replace(/(?<=\s|^)\*(?!\s)(.+?)(?<!\s)\*(?!\*)/gm, '$1')
    // Strikethrough
    .replace(/~~(.+?)~~/g, '$1')
    // Headings
    .replace(/^#{1,6}\s+/gm, '')
    // Bullet lists: - or * → •
    .replace(/^(\s*)[-*]\s+/gm, '$1\u2022 ')
    .trim();
}
