import { existsSync } from 'node:fs';
import { resolve } from 'node:path';
import type { ConfigContext, ExpoConfig } from 'expo/config';
import { oxySplashScreenPlugin } from '@oxyhq/expo-splash/config';

/**
 * Keep push credentials out of the repository while preserving local native
 * development. EAS file secrets expose a temporary path through the named
 * environment variable; local builds may use the ignored conventional file.
 * Without either file, Android still supports local notifications but does not
 * configure FCM push delivery.
 */
export default ({ config }: ConfigContext): ExpoConfig => {
  const googleServicesFile = process.env.GOOGLE_SERVICES_JSON?.trim() || './google-services.json';
  const android = { ...config.android };
  const plugins = [...(config.plugins ?? [])];

  // Keep the two Oxy splash entries adjacent and immediately after the router:
  // the shared branding plugin augments the native resources generated by
  // expo-splash-screen. Alia's supplied foreground asset has more transparent
  // padding than Mention's mark, so 212dp gives both visible symbols the same
  // on-device footprint while staying inside Android 12's safe circle.
  const splashPlugins: NonNullable<ExpoConfig['plugins']> = [
    oxySplashScreenPlugin({
      image: './assets/icon-512-maskable.png',
      imageWidth: 212,
    }),
    '@oxyhq/expo-splash',
  ];
  const routerIndex = plugins.findIndex((plugin) =>
    plugin === 'expo-router' || (Array.isArray(plugin) && plugin[0] === 'expo-router')
  );
  plugins.splice(routerIndex >= 0 ? routerIndex + 1 : 0, 0, ...splashPlugins);

  if (existsSync(resolve(__dirname, googleServicesFile))) {
    android.googleServicesFile = googleServicesFile;
  } else {
    delete android.googleServicesFile;
  }

  return {
    ...config,
    name: config.name ?? 'Alia',
    slug: config.slug ?? 'alia',
    android,
    plugins,
  };
};
