/**
 * Markdown → Telegram HTML converter
 *
 * Uses `marked` to parse standard Markdown (as generated by LLMs) and renders
 * it as Telegram Bot API compatible HTML via a custom renderer.
 *
 * Supported Telegram HTML tags:
 *   <b>, <i>, <s>, <code>, <pre>, <a href="...">, <blockquote>
 */

import { marked, Marked, type RendererObject } from 'marked';

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

const telegramRenderer: RendererObject = {
  heading({ tokens, depth }) {
    const text = this.parser.parseInline(tokens);
    return `<b>${text}</b>\n\n`;
  },

  strong({ tokens }) {
    return `<b>${this.parser.parseInline(tokens)}</b>`;
  },

  em({ tokens }) {
    return `<i>${this.parser.parseInline(tokens)}</i>`;
  },

  del({ tokens }) {
    return `<s>${this.parser.parseInline(tokens)}</s>`;
  },

  codespan({ text }) {
    return `<code>${escapeHtml(text)}</code>`;
  },

  code({ text, lang }) {
    const escaped = escapeHtml(text);
    if (lang) {
      return `<pre><code class="language-${lang}">${escaped}</code></pre>\n`;
    }
    return `<pre>${escaped}</pre>\n`;
  },

  link({ href, tokens }) {
    const text = this.parser.parseInline(tokens);
    return `<a href="${href}">${text}</a>`;
  },

  paragraph({ tokens }) {
    return `${this.parser.parseInline(tokens)}\n\n`;
  },

  list({ items, ordered }) {
    let body = '';
    for (let i = 0; i < items.length; i++) {
      const item = items[i];
      const text = this.parser.parse(item.tokens).trim();
      const prefix = ordered ? `${i + 1}. ` : '\u2022 ';
      body += `${prefix}${text}\n`;
    }
    return `${body}\n`;
  },

  listitem({ tokens }) {
    return this.parser.parse(tokens);
  },

  blockquote({ tokens }) {
    return this.parser.parse(tokens);
  },

  hr() {
    return '\n';
  },

  image() {
    return '';
  },

  br() {
    return '\n';
  },

  html() {
    return '';
  },

  table() {
    return '';
  },
  tablerow() {
    return '';
  },
  tablecell() {
    return '';
  },
};

// Create a dedicated instance so we don't pollute the global marked state
const telegramMarked = new Marked({ renderer: telegramRenderer });

/**
 * Convert standard Markdown to Telegram-compatible HTML.
 *
 * Uses `marked` for robust parsing — handles nested formatting, code blocks,
 * HTML entity escaping, and all the edge cases that regex-based converters miss.
 */
export function markdownToTelegramHtml(text: string): string {
  const html = telegramMarked.parse(text, { async: false }) as string;
  return html.trim();
}
