import { beforeEach, describe, expect, it, vi } from 'vitest';

const cryptoMock = vi.hoisted(() => ({
  getRandomValues: vi.fn<(values: Uint8Array) => Uint8Array>(),
}));

vi.mock('expo-crypto', () => cryptoMock);

import { createRandomUuid } from '../random-uuid';

describe('createRandomUuid', () => {
  beforeEach(() => {
    cryptoMock.getRandomValues.mockReset();
  });

  it('formats cryptographically generated bytes as an RFC 4122 UUID v4', () => {
    cryptoMock.getRandomValues.mockImplementation((values) => {
      values.set([
        0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0xf6, 0x77,
        0xf8, 0x99, 0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff,
      ]);
      return values;
    });

    expect(createRandomUuid()).toBe('00112233-4455-4677-b899-aabbccddeeff');
    expect(cryptoMock.getRandomValues).toHaveBeenCalledOnce();
  });

  it('requests a fresh 16-byte buffer for each identifier', () => {
    cryptoMock.getRandomValues.mockImplementation((values) => {
      values.fill(0);
      return values;
    });

    createRandomUuid();
    createRandomUuid();

    const [first, second] = cryptoMock.getRandomValues.mock.calls.map(([values]) => values);
    expect(first).toHaveLength(16);
    expect(second).toHaveLength(16);
    expect(first).not.toBe(second);
  });
});
