/**
 * Generated by `scripts/icon-shims.mjs` — do not edit by hand.
 *
 * `metro.config.js` resolves the bare `lucide-react-native` specifier to this
 * file on WEB ONLY. The real root entry re-exports all 1,747 icons, and Metro
 * does not tree shake the web export, so importing it from anywhere pulled
 * 1,836,042 B of icons into `index-*.js`. This barrel names only the icons the
 * repo imports, each from its own `./icons/*` subpath export.
 *
 * Native resolution is untouched: the redirect is gated on `platform === "web"`.
 *
 * Adding an icon import? Re-run `bun run --filter @alia/app generate:icon-shims`.
 * `__tests__/icon-shims.test.ts` fails if you forget — TypeScript will not,
 * because it resolves `lucide-react-native` to the real package.
 */

export { default as AlertTriangle } from 'lucide-react-native/icons/triangle-alert';
export { default as AppWindow } from 'lucide-react-native/icons/app-window';
export { default as Brain } from 'lucide-react-native/icons/brain';
export { default as Calendar } from 'lucide-react-native/icons/calendar';
export { default as CheckCircle } from 'lucide-react-native/icons/circle-check-big';
export { default as Database } from 'lucide-react-native/icons/database';
export { default as ExternalLink } from 'lucide-react-native/icons/external-link';
export { default as FileText } from 'lucide-react-native/icons/file-text';
export { default as Globe } from 'lucide-react-native/icons/globe';
export { default as Info } from 'lucide-react-native/icons/info';
export { default as Link } from 'lucide-react-native/icons/link';
export { default as MessageCircle } from 'lucide-react-native/icons/message-circle';
export { default as MessageSquare } from 'lucide-react-native/icons/message-square';
export { default as Search } from 'lucide-react-native/icons/search';
export { default as Send } from 'lucide-react-native/icons/send';
export { default as Settings } from 'lucide-react-native/icons/settings';
export { default as Shapes } from 'lucide-react-native/icons/shapes';
export { default as User } from 'lucide-react-native/icons/user';
export { default as Users } from 'lucide-react-native/icons/users';
export { default as XCircle } from 'lucide-react-native/icons/circle-x';

// Type-only exports: erased at compile time, so they cost no bundle bytes.
export type { LucideIcon } from 'lucide-react-native';
