/**
 * Generated by `scripts/icon-shims.mjs` — do not edit by hand.
 *
 * `metro.config.js` resolves the bare `lucide-react-native` specifier to this
 * file on WEB ONLY. The real root entry re-exports all 1,747 icons, and Metro
 * does not tree shake the web export, so importing it from anywhere pulled
 * 1,836,042 B of icons into `index-*.js`. This barrel names only the icons the
 * repo imports, each from its own `./icons/*` subpath export.
 *
 * Native resolution is untouched: the redirect is gated on `platform === "web"`.
 *
 * Adding an icon import? Re-run `bun run --filter @alia/app generate:icon-shims`.
 * `__tests__/icon-shims.test.ts` fails if you forget — TypeScript will not,
 * because it resolves `lucide-react-native` to the real package.
 */

export { default as AlertCircle } from 'lucide-react-native/icons/circle-alert';
export { default as AlertTriangle } from 'lucide-react-native/icons/triangle-alert';
export { default as AppWindow } from 'lucide-react-native/icons/app-window';
export { default as Archive } from 'lucide-react-native/icons/archive';
export { default as ArrowLeft } from 'lucide-react-native/icons/arrow-left';
export { default as ArrowRight } from 'lucide-react-native/icons/arrow-right';
export { default as ArrowUp } from 'lucide-react-native/icons/arrow-up';
export { default as Ban } from 'lucide-react-native/icons/ban';
export { default as BarChart3 } from 'lucide-react-native/icons/chart-column';
export { default as Bell } from 'lucide-react-native/icons/bell';
export { default as BellOff } from 'lucide-react-native/icons/bell-off';
export { default as BookMarked } from 'lucide-react-native/icons/book-marked';
export { default as BookOpen } from 'lucide-react-native/icons/book-open';
export { default as Bot } from 'lucide-react-native/icons/bot';
export { default as Brain } from 'lucide-react-native/icons/brain';
export { default as Briefcase } from 'lucide-react-native/icons/briefcase';
export { default as Building2 } from 'lucide-react-native/icons/building-2';
export { default as Calendar } from 'lucide-react-native/icons/calendar';
export { default as CalendarClock } from 'lucide-react-native/icons/calendar-clock';
export { default as Check } from 'lucide-react-native/icons/check';
export { default as CheckCheck } from 'lucide-react-native/icons/check-check';
export { default as CheckCircle } from 'lucide-react-native/icons/circle-check-big';
export { default as CheckCircle2 } from 'lucide-react-native/icons/circle-check';
export { default as ChevronDown } from 'lucide-react-native/icons/chevron-down';
export { default as ChevronLeft } from 'lucide-react-native/icons/chevron-left';
export { default as ChevronRight } from 'lucide-react-native/icons/chevron-right';
export { default as ChevronUp } from 'lucide-react-native/icons/chevron-up';
export { default as Circle } from 'lucide-react-native/icons/circle';
export { default as Clock } from 'lucide-react-native/icons/clock';
export { default as Code } from 'lucide-react-native/icons/code';
export { default as Coffee } from 'lucide-react-native/icons/coffee';
export { default as Coins } from 'lucide-react-native/icons/coins';
export { default as Copy } from 'lucide-react-native/icons/copy';
export { default as CreditCard } from 'lucide-react-native/icons/credit-card';
export { default as Crown } from 'lucide-react-native/icons/crown';
export { default as Database } from 'lucide-react-native/icons/database';
export { default as Download } from 'lucide-react-native/icons/download';
export { default as Ellipsis } from 'lucide-react-native/icons/ellipsis';
export { default as ExternalLink } from 'lucide-react-native/icons/external-link';
export { default as Eye } from 'lucide-react-native/icons/eye';
export { default as File } from 'lucide-react-native/icons/file';
export { default as FileArchive } from 'lucide-react-native/icons/file-archive';
export { default as FileAudio } from 'lucide-react-native/icons/file-headphone';
export { default as FileCode } from 'lucide-react-native/icons/file-code';
export { default as FileEdit } from 'lucide-react-native/icons/file-pen';
export { default as FileJson } from 'lucide-react-native/icons/file-braces';
export { default as FileSpreadsheet } from 'lucide-react-native/icons/file-spreadsheet';
export { default as FileText } from 'lucide-react-native/icons/file-text';
export { default as Flame } from 'lucide-react-native/icons/flame';
export { default as Folder } from 'lucide-react-native/icons/folder';
export { default as FolderClosed } from 'lucide-react-native/icons/folder-closed';
export { default as FolderOpen } from 'lucide-react-native/icons/folder-open';
export { default as FolderTree } from 'lucide-react-native/icons/folder-tree';
export { default as Gift } from 'lucide-react-native/icons/gift';
export { default as GitBranch } from 'lucide-react-native/icons/git-branch';
export { default as Globe } from 'lucide-react-native/icons/globe';
export { default as Globe2 } from 'lucide-react-native/icons/earth';
export { default as GraduationCap } from 'lucide-react-native/icons/graduation-cap';
export { default as HardDrive } from 'lucide-react-native/icons/hard-drive';
export { default as Heart } from 'lucide-react-native/icons/heart';
export { default as HeartHandshake } from 'lucide-react-native/icons/heart-handshake';
export { default as HelpCircle } from 'lucide-react-native/icons/circle-question-mark';
export { default as Image } from 'lucide-react-native/icons/image';
export { default as Inbox } from 'lucide-react-native/icons/inbox';
export { default as Info } from 'lucide-react-native/icons/info';
export { default as Layers } from 'lucide-react-native/icons/layers';
export { default as Lightbulb } from 'lucide-react-native/icons/lightbulb';
export { default as Link } from 'lucide-react-native/icons/link';
export { default as Link2 } from 'lucide-react-native/icons/link-2';
export { default as ListTodo } from 'lucide-react-native/icons/list-todo';
export { default as Loader } from 'lucide-react-native/icons/loader';
export { default as Loader2 } from 'lucide-react-native/icons/loader-circle';
export { default as Lock } from 'lucide-react-native/icons/lock';
export { default as LogIn } from 'lucide-react-native/icons/log-in';
export { default as MapPin } from 'lucide-react-native/icons/map-pin';
export { default as MessageCircle } from 'lucide-react-native/icons/message-circle';
export { default as MessageCircleQuestion } from 'lucide-react-native/icons/message-circle-question-mark';
export { default as MessageSquare } from 'lucide-react-native/icons/message-square';
export { default as Mic } from 'lucide-react-native/icons/mic';
export { default as Monitor } from 'lucide-react-native/icons/monitor';
export { default as MoreHorizontal } from 'lucide-react-native/icons/ellipsis';
export { default as Newspaper } from 'lucide-react-native/icons/newspaper';
export { default as Package } from 'lucide-react-native/icons/package';
export { default as Palette } from 'lucide-react-native/icons/palette';
export { default as Paperclip } from 'lucide-react-native/icons/paperclip';
export { default as Pause } from 'lucide-react-native/icons/pause';
export { default as Pencil } from 'lucide-react-native/icons/pencil';
export { default as Play } from 'lucide-react-native/icons/play';
export { default as Plug } from 'lucide-react-native/icons/plug';
export { default as Plus } from 'lucide-react-native/icons/plus';
export { default as Rocket } from 'lucide-react-native/icons/rocket';
export { default as RotateCw } from 'lucide-react-native/icons/rotate-cw';
export { default as Search } from 'lucide-react-native/icons/search';
export { default as Send } from 'lucide-react-native/icons/send';
export { default as Settings } from 'lucide-react-native/icons/settings';
export { default as Shapes } from 'lucide-react-native/icons/shapes';
export { default as Share2 } from 'lucide-react-native/icons/share-2';
export { default as Shield } from 'lucide-react-native/icons/shield';
export { default as ShieldAlert } from 'lucide-react-native/icons/shield-alert';
export { default as ShieldX } from 'lucide-react-native/icons/shield-x';
export { default as ShoppingCart } from 'lucide-react-native/icons/shopping-cart';
export { default as Smartphone } from 'lucide-react-native/icons/smartphone';
export { default as Sparkles } from 'lucide-react-native/icons/sparkles';
export { default as Square } from 'lucide-react-native/icons/square';
export { default as Star } from 'lucide-react-native/icons/star';
export { default as Target } from 'lucide-react-native/icons/target';
export { default as Terminal } from 'lucide-react-native/icons/terminal';
export { default as Trash2 } from 'lucide-react-native/icons/trash-2';
export { default as TriangleAlert } from 'lucide-react-native/icons/triangle-alert';
export { default as Unlink } from 'lucide-react-native/icons/unlink';
export { default as Upload } from 'lucide-react-native/icons/upload';
export { default as User } from 'lucide-react-native/icons/user';
export { default as Users } from 'lucide-react-native/icons/users';
export { default as WifiOff } from 'lucide-react-native/icons/wifi-off';
export { default as X } from 'lucide-react-native/icons/x';
export { default as XCircle } from 'lucide-react-native/icons/circle-x';
export { default as Zap } from 'lucide-react-native/icons/zap';

// Type-only exports: erased at compile time, so they cost no bundle bytes.
export type { LucideIcon } from 'lucide-react-native';
